var express  = require('express');
var app      = express();
var db = require('./zipcodes.js')

app.use(express.static('public/startbootstrap-full-width-pics-gh-pages'));
var cors = require('cors');
app.use(cors());


app.get('/data/:library/:park/:garden/:gallery/:store', function(req,res){
    var library_input  = req.params.library
    var park_input = req.params.park
    var garden_input = req.params.garden
    var art_input = req.params.gallery
    var store_input = req.params.store
    var result = []
    db.forEach(function(item){
        var zip = item.id
        var library_weight = (item.library_score * library_input)/100
        var park_weight = (item.park_score * park_input)/100
        var garden_weight = (item.garden_score * garden_input)/100
        var art_weight = (item.art_score * art_input)/100
        var store_weight = (item.healthy_score * store_input)/100
        var total_score = library_weight + park_weight + garden_weight + art_weight + store_weight
        result.push({zipcode: zip, score: total_score})
    })
    result.sort (function(a,b) {
        return a.score - b.score;
    })
    console.log(result)
    var first = result[result.length-1]["zipcode"]
    var second = result[result.length-2]["zipcode"]
    var third = result[result.length-3]["zipcode"]
    var myZips = [11212, 11213, 11216, 11233, 11238, 11209, 11214, 11228, 11204, 11218, 11219, 11230, 11234, 11236, 11239, 11223, 11224, 11229, 11235, 11201, 11205, 11215, 11217, 11231, 11203, 11210, 11225, 11226, 11207, 11208, 11211, 11222, 11220, 11232, 11206, 11221, 11237]

    
    // var answer = "1) " + result[result.length-1]["zipcode"] + "<br>" + "2) " + result[result.length-2]["zipcode"] + "<br>" + "3) " + result[result.length-3]["zipcode"]
        if( first == '11211'){
            var descrip = "This zipcode belongs to the neighborhood Williamsburg. Residents here have a singular flair when it comes to style, which comes part and parcel with the young, creative and energetic vibe of the area. There's no getting around it though, the neighborhood has changed rapidly over the past few decades and younger residents live among long-standing communities of Dominicans, Italians and Hasidic Jews. Quick commutes to downtown Manhattan on the L, J, and M trains mean early morning trains are packed with young professionals. Practically everywhere you look in Williamsburg there’s new construction of varying size, price and quality going up, catering to the seemingly ceaseless influx of new residents."
        }
        if (first == '11212'){
            var descrip = "This zipcode belongs to Brownsville, a residential neighborhood located in eastern Brooklyn in New York City. The 1.163-square-mile area that comprises Brownsville has 58,300 residents as of the 2010 United States Census. The neighborhood's boundaries are unclear, but it is generally bordered by Crown Heights to the northwest; Bushwick and Cypress Hills to the north; New Lots to the east; Canarsie to the south; and East Flatbush to the west. Founded in its current incarnation in 1858, initially a settlement composed of Jewish factory workers, Brownsville underwent a major demographic change in the 1950s that saw an influx of African-American and Latino residents."
        }
        if(first == '11213'){
            var descrip = "This zipcode belongs to Crown Heights - From the chaotic, commercial avenues of Nostrand and Utica to the wide, tree-lined esplanades of Eastern Parkway, the streets are always filled with locals shopping, catching up on the corner, and keeping tabs on neighbors. Crown Heights is known for its large Caribbean community, and plays host to the West Indian Day Parade, one of the city's largest annual street festivals, every Labor Day. The neighborhood is also home to one of the nation's largest Orthodox Jewish communities, centered around Kingston Avenue. The mix of cultures in such close proximity makes Crown Heights a fascinating microcosm of New York City. Living here, you'll be surrounded by a community with deep roots and rich heritage."
        }
        if(first == '11216' || first== '11233' || first=='11206'){
            var descrip = "This zipcode belongs to Bedford-Stuyvesant, a vast Brooklyn neighborhood filled with historic brownstones and Victorian architecture. Starting in the 1920s and '30s, many black families moved to Bed-Stuy from Harlem in search of more space, quieter streets and a community they could call their own. The neighborhood's leafy streets and classic brownstones have made it a favorite amid Brooklyn's ongoing resurgence. Young professionals and artists are moving in, and new restaurants, bars and businesses are cropping up along Bed-Stuy's streets and avenues."
        }
        if(first == '11238'){
            var descrip = "This zipcode belongs to Prospect Heights, which offers a vibrant mix of old and new Brooklyn, with deep-rooted African American and Caribbean communities existing alongside younger families and professionals. Prospect Heights has recently become known for its own unique personality – as well as rising real estate value. The commercial strips of Vanderbilt and Washington Avenues offer a mix of bodegas and inveterate neighborhood standbys next to a new spate of hipster-centric bars and restaurants. Turn down any side street, however, and you can encounter gorgeous old brownstones surrounded by quiet greenery."
        }
        if(first == '11209'){
            var descrip = "This zipcode belongs to Bay Ridge, the neighborhood where 'Saturday Night Fever' was set. Bay Ridge has resisted the wave of gentrification sweeping through much of Brooklyn. Though becoming popular with a younger crowd, Bay Ridge remains a haven for long-term residents, local businesses and working-class families. The Verrazano-Narrows Bridge dominates the skyline, and single-family row houses make up the majority of the housing stock. Renters pushed out of Park Slope find a similar community vibe here, at a decidedly lower price."
        }
        if(first == '11214' || first=='11204'){
            var descrip = "This zipcode belongs to Bensonhurst-- a large, multiethnic neighborhood in the southwestern part of the New York City borough of Brooklyn. It is bounded by 14th Avenue to the northwest, 60th Street and McDonald Avenue to the northeast, 86th Street to the southwest, and 25th Avenue and Avenue P to the southeast. Bensonhurst's adjacent neighborhoods include Dyker Heights to the northwest, Borough Park and Mapleton to the northeast, Bath Beach to the southwest, and Gravesend to the southeast. Bensonhurst is known as a Little Italy of Brooklyn due to its large Italian-American population. Bensonhurst also has the largest population of residents born in China of any neighborhood in New York City and is now home to Brooklyn's second Chinatown."
        }
        if(first == '11228'){
            var descrip = "This zipcode belongs to Dyker Heights, a middle-class, largely Italian-American neighborhood in southwestern Brooklyn, that bears signs throughout the year of a place that people deeply care for. In warm-weather months, blocks throw parties — the kind featuring three-legged races and barbecues. In tiny front yards that might have been paved over elsewhere, bushes are neatly trimmed to keep their corkscrew shapes. In December, Dyker Heights — 55,000 residents over one and a half square miles — takes its pride of place to a new and electrifying level. Known as “Dyker Lights,” it’s a vivid tribute to the season, in which yards are filled with a universe of bulbs, garlands, and more than a few life-size “Nutcracker”-style soldiers."
        }
        if(first == '11218'){
            var descrip = "This zipcode belongs to Kensington, a predominantly residential area that consists of housing types that run the gamut from brick rowhouses to detached one-family Victorians to apartment buildings. Pre-war brick apartment buildings dominate the Ocean Parkway and Coney Island Avenue frontage, including many that operate as co-ops. The main commercial streets are Coney Island Avenue, Church Avenue, Ditmas Avenue and McDonald Avenue. Kensington is a very diverse neighborhood, containing African-American, Ukrainian, South Asian (Bangladeshi and Pakistani), Chinese, Orthodox Jewish, Hasidic, Irish, Polish, Italian, Albanian, Russian, Latino, Mexican, Australian and Caribbean communities."
        }
        if(first == '11219'){
            var descrip = "This zipcode belongs to Borough Park, a neighborhood in the southwestern part of the borough of Brooklyn, in New York City, United States. The neighborhood is bordered by Bensonhurst to the south, Bay Ridge to the southwest, Sunset Park to the west, Kensington and Green-Wood Cemetery to the northeast, Flatbush to the east, and Midwood to the southeast. Borough Park is home to one of the largest Orthodox Jewish communities outside Israel, with one of the largest concentrations of Jews in the United States, and Orthodox traditions rivaling many insular communities. Borough Park is experiencing a sharp growth in population and it is an economically diverse neighborhood."
        }
        if(first == '11230'){
            var descrip = "This zipcode belongs to Midwood, a neighborhood in the south-central part of the New York City borough of Brooklyn. It is bounded on the north by the Bay Ridge Branch tracks just above Avenue I and by the Brooklyn College campus of the City University of New York, and on the south by Avenue P and Kings Highway. The eastern border consists of parts of Nostrand Avenue, Flatbush Avenue, and Coney Island Avenue; parts of McDonald Avenue and Ocean Parkway mark the western boundary."
        }
        if(first == '11234'){
            var descrip = "This zipcode belongs to Mill Basin, a residential neighborhood in the southeastern part of Brooklyn, New York City. It is located on a peninsula abutting Jamaica Bay and is bordered by Avenue U on the north and the Mill Basin/Mill Island Inlet on the south, east and west. The area is part of Brooklyn Community Board 18. Mill Basin was originally Mill Island, located in Jamaica Bay. In the 17th century, a mill was built on the island by Elbert Elbertse, who occupied Mill Island as well as the nearby Bergen and Barren Islands. Industrial customers started developing the island and connected it to the rest of Brooklyn."
        }
        if(first == '11236'){
            var descrip = "This zipcode belongs to Canarsie, a working- and middle-class residential and commercial neighborhood in the southeastern portion of the borough of Brooklyn, in New York City, United States. Canarsie is bordered on the east by Fresh Creek Basin, East 108th Street, and the BMT Canarsie Line (L train); on the north by Linden Boulevard; on the west by Remsen Avenue to Ralph Avenue and the Paerdegat Basin; and on the south by Jamaica Bay. It is adjacent to the East Flatbush, Flatlands, Mill Basin, Bergen Beach, and East New York neighborhoods."
        }
        if(first == '11239'){
            var descrip = "This zipcode belongs to Spring Creek. For most of its history Spring Creek was considered the place where 'the city came to an end', consisting of undeveloped marshland used as illegal dumping grounds, and hosting several large landfills and an incinerator during the 20th century. Much of the area was designated as the Fresh Creek Urban Renewal Area in 1967. The area has since seen several major development and restoration projects, including the Starrett City apartment complex, the Gateway Center shopping complex, several affordable housing communities, and Spring Creek Park. Spring Creek had the largest net gain in population in Brooklyn between 1940 and 2010, an increase of 330%."
        }
        if(first == '11223'){
            var descrip = "This zipcode belongs to Gravesend, a neighborhood in the south-central section of Brooklyn, on the southwestern edge of Long Island. It is bounded on the south by Coney Island, on the west by Bath Beach, on the north by Bensonhurst, and on the east by Homecrest and Sheepshead Bay. Gravesend was one of the original towns in the Dutch colony of New Netherland. After the English took over, it was one of the six original towns of Kings County in colonial New York. Gravesend was the only English chartered town in what became Kings County, and is notable as being one of the first towns founded by a woman, Lady Deborah Moody. The Town of Gravesend encompassed 7,000 acres in southern Kings County, including the entire island of Coney Island, and was annexed by the City of Brooklyn in 1894. The modern-day neighborhood is part of Brooklyn Community Board 11. As of 2010, Gravesend had a population of 29,436"
        }
        if(first == '11224'){
            var descrip = "This zipcode belongs to Coney Island, a residential and commercial neighborhood and entertainment area in the southwestern part of the borough of Brooklyn in New York City. The neighborhood is bounded by Sea Gate to its west, Brighton Beach and Manhattan Beach to its east, Lower New York Bay to the south, and Gravesend to the north. Coney Island was formerly the westernmost of the Outer Barrier islands on the southern shore of Long Island, but in the early 20th century it became a peninsula, connected to the rest of Long Island by land fill. Coney Island has 31,965 residents as of the 2010 United States Census. The neighborhood is ethnically diverse."
        }
        if(first == '11229' || first=='11235'){
            var descrip = "This zipcode belongs to Sheepshead Bay, a neighborhood in southern Brooklyn, New York City. It is bounded by Ocean Parkway to the west; Avenue T and Kings Highway to the north; Nostrand Avenue and Gerritsen Avenue to the east; and the Atlantic Ocean to the south. Sheepshead Bay is abutted by the neighborhoods of Brighton Beach and Homecrest to the west; Midwood to the north; and Gerritsen Beach to the east. The neighborhood is named after a bay that separates mainland Brooklyn from the eastern portion of Coney Island, which was originally one of the Outer Barrier islands but is now a peninsula. The mouth of the bay is about 1.0 mile southwest of Marine Park"
        }
        if(first == '11201'){
            var descrip = "This zipcode belongs to Brooklyn Heights, which is as well-known for its gorgeous housing stock as for its impressive backdrop and scenery. The Promenade is the neighborhood’s most celebrated and popular public space, offering just about the best views of the Brooklyn Bridge and the Manhattan skyline that can be found. There, you’re likely to find locals walking their Westies, kids zooming around on scooters, and tourists excitedly snapping pics — every one of them savoring the views from this prime perch of a neighborhood. "
        }
        if(first == '11205'){
            var descrip = "This zipcode belongs to Clinton Hill, a neighborhood in north-central Brooklyn. It is bordered by the Brooklyn Navy Yard and the Brooklyn-Queens Expressway to the north, Williamsburg to the northeast, Classon Avenue and Bedford–Stuyvesant to the east, Atlantic Avenue and Prospect Heights to the south and southwest and Vanderbilt Avenue and Fort Greene to the west.The neighborhood is served by the NYPD's 88th Precinct.'The Hill', as the general area was known – with a maximum elevation of 95 feet, the highest in the area– was believed to have health benefits because many people believed that disease was more prevalent in low-lying areas. The area is named after Clinton Avenue, which in turn was named in honor of New York Governor DeWitt Clinton (1769–1828). The affluent neighborhood's mixture of apartment buildings, mansions, brownstone and brick rowhouses, and the Pratt Institute and St. Joseph's College, built at various times in a number of different styles, is a great part of its charm. "
        }
        if(first == '11215'){
            var descrip = "This zipcode belongs to Park Slope, which has a tranquil, easygoing vibe and can almost feel suburban. Strollers and children of all ages are a constant presence on sidewalks, as are shoppers patronizing local boutiques and dog walkers heading up to the park. Residents are Brooklynites through and through, and tend to be socially conscious, artistically minded and committed to their community. At night, a casual restaurant scene comes alive. For anyone looking for a night out, there are plenty of beer gardens and wine bars to patronize, especially in the South Slope. "
        }
        if(first == '11217'){
            var descrip = "This zipcode belongs to Boerum Hill. With wide tree-lined streets, stately Greek revival and Italianate townhouses, and a mix of designer boutiques and upscale restaurants, Boerum Hill exudes an effortlessly elegant appeal. While the neighborhood’s culture, shopping and nightlife rival that of Downtown Manhattan, the clusters of strollers quickly give it away as brownstone Brooklyn. The neighborhood's current atmosphere, however, belies its somewhat gritty history. Until the 1980s, the neighborhood was firmly working class, with many of its largest homes divided into boarding houses or used as union halls. Crime was high, and empty lots abounded. Revitalization efforts, coupled with the neighborhood’s natural assets — its proximity to Manhattan and beautiful housing stock — helped transformed Boerum Hill into one of Brooklyn’s most desirable neighborhoods. With low turnover rates, homes in Boerum Hill are now in constant demand. "
        }
        if(first == '11231'){
            var descrip = "This zipcode belongs to Carroll Gardens, which is at once the heart of old-school Brooklyn and a showcase for the borough's brownstone boom. The neighborhood has long been known for its red-sauce Italian joints and lively street life. But now, neighborhood staples like Caputo’s Bake Shop and Monteleone’s Bakery and Café abut upscale stroller shops, yoga studios and fro-yo joints. Despite the newcomers, the neighborhood still feels like a small town, one of the few places where you'll know your neighbors, your postman and your butcher by name. "
        }
        if(first == '11203' || first=='11210'){
            var descrip = "This zipcode belongs to East Flatbush, a residential neighborhood in Brooklyn. The area is part of Brooklyn Community Board 17. East Flatbush is patrolled by the NYPD's 67th Precinct. East Flatbush is bounded by Crown Heights and Empire Boulevard to the north; Brownsville and East 98th Street to the east; Flatlands and the Long Island Rail Road's Bay Ridge Branch to the south; and Flatbush and Bedford/Nostrand Avenues to the west. East Flatbush is a predominantly African American neighborhood and has a population of 135,619 as of the 2010 United States Census "
        }
        if(first == '11225'){
            var descrip = "This zipcode belongs to Prospect Leffers Gardens, a residential neighborhood in the Flatbush area of Brooklyn. The community is bounded by Empire Boulevard (formerly Malbone Street) to the north, Clarkson Avenue to the south, New York Avenue to the east, and Ocean Avenue/Prospect Park to the west. Prospect Lefferts Gardens was designated a NYC Landmark area in 1979 and called the Prospect Lefferts Gardens Historic District. The neighborhood contains an ethnically diverse community with a largely Caribbean-American and African-American population. Since the 2000s, Prospect Lefferts Gardens has been gentrifying quickly. Real estate development has increased and new residents from other groups have increased "
        }
        if(first == '11226'){
            var descrip = "This zipcode belongs to Flatbush, founded in 1651 by Dutch colonists. The neighborhood, which consists of several subsections, had a population of 110,875 as of the 2010 United States Census. Flatbush was a town prior to being incorporated into the City of Brooklyn, and its former border runs through the Brooklyn Botanic Garden. Generally, the township was larger than what is considered Flatbush today by the residents of Brooklyn. The modern neighborhood includes or borders several institutions of note, including Prospect Park and Brooklyn College "
        }
        if(first == '11207' || first=='11208'){
            var descrip = "This zipcode belongs to East New York, a residential neighborhood in the eastern section of Brooklyn. Its boundaries, starting from the north and moving clockwise are: Cypress Hills Cemetery to the north, the Borough of Queens to the east, Jamaica Bay to the south, and the Bay Ridge Branch railway tracks next to Van Sinderen Avenue to the west. Linden Boulevard and Atlantic Avenue are the primary thoroughfares through East New York. East New York was founded as the Town of New Lots in the 1650s. It was annexed as the 26th Ward of the rapidly growing City of Brooklyn in 1886, and became part of New York City in 1898. During the latter part of the twentieth century, East New York came to be predominantly inhabited by African Americans and Latinos "
        }
        if(first == '11222'){
            var descrip = "This zipcode belongs to the neighborhood Greenpoint. A former industrial and maritime neighborhood, Greenpoint was once primarily home to Polish and Irish immigrants and is now home to a large artist's community. The nightlife, restaurant and music scene have burgeoned in recent years as energy and activity in Williamsburg creeps north towards Greenpoint. Despite all the change that’s happened already and the clear potential for greater change to come, Greenpoint still hangs onto its rich history and an old-school community. Greenpoint maintains a large Polish community and as such has some of the city's best and most authentic butchers. A treasure trove of aging industrial architecture, Greenpoint is also full of impressive old warehouses, brick smokestacks and rusting water tanks. "
        }
        if(first == '11220' || first == '11232'){
            var descrip = "This zipcode belongs to the neighborhood Sunset Park. Tucked between Park Slope and Bay Ridge, Sunset Park is a bit of a hike from Manhattan and Downtown Brooklyn. Relative obscurity has kept rents low for decades, although that appears to be slowly changing as brownstone families are priced out of Park Slope and Carroll Gardens. Popular with immigrants, Sunset Park has a thriving Chinese and Latin American community with great restaurants to match. Closer to the water, a new hipster wave is beginning; Industry City, a cluster of 16 warehouses on cobblestone streets, now hosts Smorgasburg, The Brooklyn Flea, and Mister Sunday, a day dance party in the summer. The galleries, tech conferences, rooftop movie screenings and countless artisan shops in that complex are slowly putting Sunset Park on the map for young people "
        }
        if(first == '11221' || first=='11237'){
            var descrip = "This zipcode belongs to the neighborhood Bushwick, which has seen a lot of change over the years. In the early 1900s, it was known for its thriving distilleries and breweries. After those industries declined, it experienced a long period of blight through the 1970s and '80s. Now the neighborhood is seeing a renaissance, as artists pushed out of Williamsburg and elsewhere move in and raise property values. Bushwick is a perfect place for those seeking unconventional living spaces: The housing market is full of converted lofts in old factories, sometimes with great access to outdoor space. "
        }
        // second ------------------------------------------------------------
        if( second == '11211'){
            var descrip2 = "This zipcode belongs to the neighborhood Williamsburg. Residents here have a singular flair when it comes to style, which comes part and parcel with the young, creative and energetic vibe of the area. There's no getting around it though, the neighborhood has changed rapidly over the past few decades and younger residents live among long-standing communities of Dominicans, Italians and Hasidic Jews. Quick commutes to downtown Manhattan on the L, J, and M trains mean early morning trains are packed with young professionals. Practically everywhere you look in Williamsburg there’s new construction of varying size, price and quality going up, catering to the seemingly ceaseless influx of new residents."
        }
        if (second == '11212'){
            var descrip2 = "This zipcode belongs to Brownsville, a residential neighborhood located in eastern Brooklyn in New York City. The 1.163-square-mile area that comprises Brownsville has 58,300 residents as of the 2010 United States Census. The neighborhood's boundaries are unclear, but it is generally bordered by Crown Heights to the northwest; Bushwick and Cypress Hills to the north; New Lots to the east; Canarsie to the south; and East Flatbush to the west. Founded in its current incarnation in 1858, initially a settlement composed of Jewish factory workers, Brownsville underwent a major demographic change in the 1950s that saw an influx of African-American and Latino residents."
        }
        if(second == '11213'){
            var descrip2 = "This zipcode belongs to Crown Heights - From the chaotic, commercial avenues of Nostrand and Utica to the wide, tree-lined esplanades of Eastern Parkway, the streets are always filled with locals shopping, catching up on the corner, and keeping tabs on neighbors. Crown Heights is known for its large Caribbean community, and plays host to the West Indian Day Parade, one of the city's largest annual street festivals, every Labor Day. The neighborhood is also home to one of the nation's largest Orthodox Jewish communities, centered around Kingston Avenue. The mix of cultures in such close proximity makes Crown Heights a fascinating microcosm of New York City. Living here, you'll be surrounded by a community with deep roots and rich heritage."
        }
        if(second == '11216' || second== '11233' || second=='11206'){
            var descrip2 = "This zipcode belongs to Bedford-Stuyvesant, a vast Brooklyn neighborhood filled with historic brownstones and Victorian architecture. Starting in the 1920s and '30s, many black families moved to Bed-Stuy from Harlem in search of more space, quieter streets and a community they could call their own. The neighborhood's leafy streets and classic brownstones have made it a favorite amid Brooklyn's ongoing resurgence. Young professionals and artists are moving in, and new restaurants, bars and businesses are cropping up along Bed-Stuy's streets and avenues."
        }
        if(second == '11238'){
            var descrip2 = "This zipcode belongs to Prospect Heights, which offers a vibrant mix of old and new Brooklyn, with deep-rooted African American and Caribbean communities existing alongside younger families and professionals. Prospect Heights has recently become known for its own unique personality – as well as rising real estate value. The commercial strips of Vanderbilt and Washington Avenues offer a mix of bodegas and inveterate neighborhood standbys next to a new spate of hipster-centric bars and restaurants. Turn down any side street, however, and you can encounter gorgeous old brownstones surrounded by quiet greenery."
        }
        if(second == '11209'){
            var descrip2 = "This zipcode belongs to Bay Ridge, the neighborhood where 'Saturday Night Fever' was set. Bay Ridge has resisted the wave of gentrification sweeping through much of Brooklyn. Though becoming popular with a younger crowd, Bay Ridge remains a haven for long-term residents, local businesses and working-class families. The Verrazano-Narrows Bridge dominates the skyline, and single-family row houses make up the majority of the housing stock. Renters pushed out of Park Slope find a similar community vibe here, at a decidedly lower price."
        }
        if(second == '11214' || second=='11204'){
            var descrip2 = "This zipcode belongs to Bensonhurst-- a large, multiethnic neighborhood in the southwestern part of the New York City borough of Brooklyn. It is bounded by 14th Avenue to the northwest, 60th Street and McDonald Avenue to the northeast, 86th Street to the southwest, and 25th Avenue and Avenue P to the southeast. Bensonhurst's adjacent neighborhoods include Dyker Heights to the northwest, Borough Park and Mapleton to the northeast, Bath Beach to the southwest, and Gravesend to the southeast. Bensonhurst is known as a Little Italy of Brooklyn due to its large Italian-American population. Bensonhurst also has the largest population of residents born in China of any neighborhood in New York City and is now home to Brooklyn's second Chinatown."
        }
        if(second == '11228'){
            var descrip2 = "This zipcode belongs to Dyker Heights, a middle-class, largely Italian-American neighborhood in southwestern Brooklyn, that bears signs throughout the year of a place that people deeply care for. In warm-weather months, blocks throw parties — the kind featuring three-legged races and barbecues. In tiny front yards that might have been paved over elsewhere, bushes are neatly trimmed to keep their corkscrew shapes. In December, Dyker Heights — 55,000 residents over one and a half square miles — takes its pride of place to a new and electrifying level. Known as “Dyker Lights,” it’s a vivid tribute to the season, in which yards are filled with a universe of bulbs, garlands, and more than a few life-size “Nutcracker”-style soldiers."
        }
        if(second == '11218'){
            var descrip2 = "This zipcode belongs to Kensington, a predominantly residential area that consists of housing types that run the gamut from brick rowhouses to detached one-family Victorians to apartment buildings. Pre-war brick apartment buildings dominate the Ocean Parkway and Coney Island Avenue frontage, including many that operate as co-ops. The main commercial streets are Coney Island Avenue, Church Avenue, Ditmas Avenue and McDonald Avenue. Kensington is a very diverse neighborhood, containing African-American, Ukrainian, South Asian (Bangladeshi and Pakistani), Chinese, Orthodox Jewish, Hasidic, Irish, Polish, Italian, Albanian, Russian, Latino, Mexican, Australian and Caribbean communities."
        }
        if(second == '11219'){
            var descrip2 = "This zipcode belongs to Borough Park, a neighborhood in the southwestern part of the borough of Brooklyn, in New York City, United States. The neighborhood is bordered by Bensonhurst to the south, Bay Ridge to the southwest, Sunset Park to the west, Kensington and Green-Wood Cemetery to the northeast, Flatbush to the east, and Midwood to the southeast. Borough Park is home to one of the largest Orthodox Jewish communities outside Israel, with one of the largest concentrations of Jews in the United States, and Orthodox traditions rivaling many insular communities. Borough Park is experiencing a sharp growth in population and it is an economically diverse neighborhood."
        }
        if(second == '11230'){
            var descrip2 = "This zipcode belongs to Midwood, a neighborhood in the south-central part of the New York City borough of Brooklyn. It is bounded on the north by the Bay Ridge Branch tracks just above Avenue I and by the Brooklyn College campus of the City University of New York, and on the south by Avenue P and Kings Highway. The eastern border consists of parts of Nostrand Avenue, Flatbush Avenue, and Coney Island Avenue; parts of McDonald Avenue and Ocean Parkway mark the western boundary."
        }
        if(second == '11234'){
            var descrip2 = "This zipcode belongs to Mill Basin, a residential neighborhood in the southeastern part of Brooklyn, New York City. It is located on a peninsula abutting Jamaica Bay and is bordered by Avenue U on the north and the Mill Basin/Mill Island Inlet on the south, east and west. The area is part of Brooklyn Community Board 18. Mill Basin was originally Mill Island, located in Jamaica Bay. In the 17th century, a mill was built on the island by Elbert Elbertse, who occupied Mill Island as well as the nearby Bergen and Barren Islands. Industrial customers started developing the island and connected it to the rest of Brooklyn."
        }
        if(second == '11236'){
            var descrip2 = "This zipcode belongs to Canarsie, a working- and middle-class residential and commercial neighborhood in the southeastern portion of the borough of Brooklyn, in New York City, United States. Canarsie is bordered on the east by Fresh Creek Basin, East 108th Street, and the BMT Canarsie Line (L train); on the north by Linden Boulevard; on the west by Remsen Avenue to Ralph Avenue and the Paerdegat Basin; and on the south by Jamaica Bay. It is adjacent to the East Flatbush, Flatlands, Mill Basin, Bergen Beach, and East New York neighborhoods."
        }
        if(second == '11239'){
            var descrip2 = "This zipcode belongs to Spring Creek. For most of its history Spring Creek was considered the place where 'the city came to an end', consisting of undeveloped marshland used as illegal dumping grounds, and hosting several large landfills and an incinerator during the 20th century. Much of the area was designated as the Fresh Creek Urban Renewal Area in 1967. The area has since seen several major development and restoration projects, including the Starrett City apartment complex, the Gateway Center shopping complex, several affordable housing communities, and Spring Creek Park. Spring Creek had the largest net gain in population in Brooklyn between 1940 and 2010, an increase of 330%."
        }
        if(second == '11223'){
            var descrip2 = "This zipcode belongs to Gravesend, a neighborhood in the south-central section of Brooklyn, on the southwestern edge of Long Island. It is bounded on the south by Coney Island, on the west by Bath Beach, on the north by Bensonhurst, and on the east by Homecrest and Sheepshead Bay. Gravesend was one of the original towns in the Dutch colony of New Netherland. After the English took over, it was one of the six original towns of Kings County in colonial New York. Gravesend was the only English chartered town in what became Kings County, and is notable as being one of the first towns founded by a woman, Lady Deborah Moody. The Town of Gravesend encompassed 7,000 acres in southern Kings County, including the entire island of Coney Island, and was annexed by the City of Brooklyn in 1894. The modern-day neighborhood is part of Brooklyn Community Board 11. As of 2010, Gravesend had a population of 29,436"
        }
        if(second == '11224'){
            var descrip2 = "This zipcode belongs to Coney Island, a residential and commercial neighborhood and entertainment area in the southwestern part of the borough of Brooklyn in New York City. The neighborhood is bounded by Sea Gate to its west, Brighton Beach and Manhattan Beach to its east, Lower New York Bay to the south, and Gravesend to the north. Coney Island was formerly the westernmost of the Outer Barrier islands on the southern shore of Long Island, but in the early 20th century it became a peninsula, connected to the rest of Long Island by land fill. Coney Island has 31,965 residents as of the 2010 United States Census. The neighborhood is ethnically diverse."
        }
        if(second == '11229' || second=='11235'){
            var descrip2 = "This zipcode belongs to Sheepshead Bay, a neighborhood in southern Brooklyn, New York City. It is bounded by Ocean Parkway to the west; Avenue T and Kings Highway to the north; Nostrand Avenue and Gerritsen Avenue to the east; and the Atlantic Ocean to the south. Sheepshead Bay is abutted by the neighborhoods of Brighton Beach and Homecrest to the west; Midwood to the north; and Gerritsen Beach to the east. The neighborhood is named after a bay that separates mainland Brooklyn from the eastern portion of Coney Island, which was originally one of the Outer Barrier islands but is now a peninsula. The mouth of the bay is about 1.0 mile southwest of Marine Park"
        }
        if(second == '11201'){
            var descrip2 = "This zipcode belongs to Brooklyn Heights, which is as well-known for its gorgeous housing stock as for its impressive backdrop and scenery. The Promenade is the neighborhood’s most celebrated and popular public space, offering just about the best views of the Brooklyn Bridge and the Manhattan skyline that can be found. There, you’re likely to find locals walking their Westies, kids zooming around on scooters, and tourists excitedly snapping pics — every one of them savoring the views from this prime perch of a neighborhood. "
        }
        if(second == '11205'){
            var descrip2 = "This zipcode belongs to Clinton Hill, a neighborhood in north-central Brooklyn. It is bordered by the Brooklyn Navy Yard and the Brooklyn-Queens Expressway to the north, Williamsburg to the northeast, Classon Avenue and Bedford–Stuyvesant to the east, Atlantic Avenue and Prospect Heights to the south and southwest and Vanderbilt Avenue and Fort Greene to the west.The neighborhood is served by the NYPD's 88th Precinct.'The Hill', as the general area was known – with a maximum elevation of 95 feet, the highest in the area– was believed to have health benefits because many people believed that disease was more prevalent in low-lying areas. The area is named after Clinton Avenue, which in turn was named in honor of New York Governor DeWitt Clinton (1769–1828). The affluent neighborhood's mixture of apartment buildings, mansions, brownstone and brick rowhouses, and the Pratt Institute and St. Joseph's College, built at various times in a number of different styles, is a great part of its charm. "
        }
        if(second == '11215'){
            var descrip2 = "This zipcode belongs to Park Slope, which has a tranquil, easygoing vibe and can almost feel suburban. Strollers and children of all ages are a constant presence on sidewalks, as are shoppers patronizing local boutiques and dog walkers heading up to the park. Residents are Brooklynites through and through, and tend to be socially conscious, artistically minded and committed to their community. At night, a casual restaurant scene comes alive. For anyone looking for a night out, there are plenty of beer gardens and wine bars to patronize, especially in the South Slope. "
        }
        if(second == '11217'){
            var descrip2 = "This zipcode belongs to Boerum Hill. With wide tree-lined streets, stately Greek revival and Italianate townhouses, and a mix of designer boutiques and upscale restaurants, Boerum Hill exudes an effortlessly elegant appeal. While the neighborhood’s culture, shopping and nightlife rival that of Downtown Manhattan, the clusters of strollers quickly give it away as brownstone Brooklyn. The neighborhood's current atmosphere, however, belies its somewhat gritty history. Until the 1980s, the neighborhood was firmly working class, with many of its largest homes divided into boarding houses or used as union halls. Crime was high, and empty lots abounded. Revitalization efforts, coupled with the neighborhood’s natural assets — its proximity to Manhattan and beautiful housing stock — helped transformed Boerum Hill into one of Brooklyn’s most desirable neighborhoods. With low turnover rates, homes in Boerum Hill are now in constant demand. "
        }
        if(second == '11231'){
            var descrip2 = "This zipcode belongs to Carroll Gardens, which is at once the heart of old-school Brooklyn and a showcase for the borough's brownstone boom. The neighborhood has long been known for its red-sauce Italian joints and lively street life. But now, neighborhood staples like Caputo’s Bake Shop and Monteleone’s Bakery and Café abut upscale stroller shops, yoga studios and fro-yo joints. Despite the newcomers, the neighborhood still feels like a small town, one of the few places where you'll know your neighbors, your postman and your butcher by name. "
        }
        if(second == '11203' || second=='11210'){
            var descrip2 = "This zipcode belongs to East Flatbush, a residential neighborhood in Brooklyn. The area is part of Brooklyn Community Board 17. East Flatbush is patrolled by the NYPD's 67th Precinct. East Flatbush is bounded by Crown Heights and Empire Boulevard to the north; Brownsville and East 98th Street to the east; Flatlands and the Long Island Rail Road's Bay Ridge Branch to the south; and Flatbush and Bedford/Nostrand Avenues to the west. East Flatbush is a predominantly African American neighborhood and has a population of 135,619 as of the 2010 United States Census "
        }
        if(second == '11225'){
            var descrip2 = "This zipcode belongs to Prospect Leffers Gardens, a residential neighborhood in the Flatbush area of Brooklyn. The community is bounded by Empire Boulevard (formerly Malbone Street) to the north, Clarkson Avenue to the south, New York Avenue to the east, and Ocean Avenue/Prospect Park to the west. Prospect Lefferts Gardens was designated a NYC Landmark area in 1979 and called the Prospect Lefferts Gardens Historic District. The neighborhood contains an ethnically diverse community with a largely Caribbean-American and African-American population. Since the 2000s, Prospect Lefferts Gardens has been gentrifying quickly. Real estate development has increased and new residents from other groups have increased "
        }
        if(second == '11226'){
            var descrip2 = "This zipcode belongs to Flatbush, founded in 1651 by Dutch colonists. The neighborhood, which consists of several subsections, had a population of 110,875 as of the 2010 United States Census. Flatbush was a town prior to being incorporated into the City of Brooklyn, and its former border runs through the Brooklyn Botanic Garden. Generally, the township was larger than what is considered Flatbush today by the residents of Brooklyn. The modern neighborhood includes or borders several institutions of note, including Prospect Park and Brooklyn College "
        }
        if(second == '11207' || second=='11208'){
            var descrip2 = "This zipcode belongs to East New York, a residential neighborhood in the eastern section of Brooklyn. Its boundaries, starting from the north and moving clockwise are: Cypress Hills Cemetery to the north, the Borough of Queens to the east, Jamaica Bay to the south, and the Bay Ridge Branch railway tracks next to Van Sinderen Avenue to the west. Linden Boulevard and Atlantic Avenue are the primary thoroughfares through East New York. East New York was founded as the Town of New Lots in the 1650s. It was annexed as the 26th Ward of the rapidly growing City of Brooklyn in 1886, and became part of New York City in 1898. During the latter part of the twentieth century, East New York came to be predominantly inhabited by African Americans and Latinos "
        }
        if(second == '11222'){
            var descrip2 = "This zipcode belongs to the neighborhood Greenpoint. A former industrial and maritime neighborhood, Greenpoint was once primarily home to Polish and Irish immigrants and is now home to a large artist's community. The nightlife, restaurant and music scene have burgeoned in recent years as energy and activity in Williamsburg creeps north towards Greenpoint. Despite all the change that’s happened already and the clear potential for greater change to come, Greenpoint still hangs onto its rich history and an old-school community. Greenpoint maintains a large Polish community and as such has some of the city's best and most authentic butchers. A treasure trove of aging industrial architecture, Greenpoint is also full of impressive old warehouses, brick smokestacks and rusting water tanks. "
        }
        if(second == '11220' || second == '11232'){
            var descrip2 = "This zipcode belongs to the neighborhood Sunset Park. Tucked between Park Slope and Bay Ridge, Sunset Park is a bit of a hike from Manhattan and Downtown Brooklyn. Relative obscurity has kept rents low for decades, although that appears to be slowly changing as brownstone families are priced out of Park Slope and Carroll Gardens. Popular with immigrants, Sunset Park has a thriving Chinese and Latin American community with great restaurants to match. Closer to the water, a new hipster wave is beginning; Industry City, a cluster of 16 warehouses on cobblestone streets, now hosts Smorgasburg, The Brooklyn Flea, and Mister Sunday, a day dance party in the summer. The galleries, tech conferences, rooftop movie screenings and countless artisan shops in that complex are slowly putting Sunset Park on the map for young people "
        }
        if(second == '11221' || second=='11237'){
            var descrip2 = "This zipcode belongs to the neighborhood Bushwick, which has seen a lot of change over the years. In the early 1900s, it was known for its thriving distilleries and breweries. After those industries declined, it experienced a long period of blight through the 1970s and '80s. Now the neighborhood is seeing a renaissance, as artists pushed out of Williamsburg and elsewhere move in and raise property values. Bushwick is a perfect place for those seeking unconventional living spaces: The housing market is full of converted lofts in old factories, sometimes with great access to outdoor space. "
        }
        //third-------------------------------------------------------------------
        if( third == '11211'){
            var descrip3 = "This zipcode belongs to the neighborhood Williamsburg. Residents here have a singular flair when it comes to style, which comes part and parcel with the young, creative and energetic vibe of the area. There's no getting around it though, the neighborhood has changed rapidly over the past few decades and younger residents live among long-standing communities of Dominicans, Italians and Hasidic Jews. Quick commutes to downtown Manhattan on the L, J, and M trains mean early morning trains are packed with young professionals. Practically everywhere you look in Williamsburg there’s new construction of varying size, price and quality going up, catering to the seemingly ceaseless influx of new residents."
        }
        if (third == '11212'){
            var descrip3 = "This zipcode belongs to Brownsville, a residential neighborhood located in eastern Brooklyn in New York City. The 1.163-square-mile area that comprises Brownsville has 58,300 residents as of the 2010 United States Census. The neighborhood's boundaries are unclear, but it is generally bordered by Crown Heights to the northwest; Bushwick and Cypress Hills to the north; New Lots to the east; Canarsie to the south; and East Flatbush to the west. Founded in its current incarnation in 1858, initially a settlement composed of Jewish factory workers, Brownsville underwent a major demographic change in the 1950s that saw an influx of African-American and Latino residents."
        }
        if(third == '11213'){
            var descrip3 = "This zipcode belongs to Crown Heights - From the chaotic, commercial avenues of Nostrand and Utica to the wide, tree-lined esplanades of Eastern Parkway, the streets are always filled with locals shopping, catching up on the corner, and keeping tabs on neighbors. Crown Heights is known for its large Caribbean community, and plays host to the West Indian Day Parade, one of the city's largest annual street festivals, every Labor Day. The neighborhood is also home to one of the nation's largest Orthodox Jewish communities, centered around Kingston Avenue. The mix of cultures in such close proximity makes Crown Heights a fascinating microcosm of New York City. Living here, you'll be surrounded by a community with deep roots and rich heritage."
        }
        if(third == '11216' || third== '11233' || third=='11206'){
            var descrip3 = "This zipcode belongs to Bedford-Stuyvesant, a vast Brooklyn neighborhood filled with historic brownstones and Victorian architecture. Starting in the 1920s and '30s, many black families moved to Bed-Stuy from Harlem in search of more space, quieter streets and a community they could call their own. The neighborhood's leafy streets and classic brownstones have made it a favorite amid Brooklyn's ongoing resurgence. Young professionals and artists are moving in, and new restaurants, bars and businesses are cropping up along Bed-Stuy's streets and avenues."
        }
        if(third == '11238'){
            var descrip3 = "This zipcode belongs to Prospect Heights, which offers a vibrant mix of old and new Brooklyn, with deep-rooted African American and Caribbean communities existing alongside younger families and professionals. Prospect Heights has recently become known for its own unique personality – as well as rising real estate value. The commercial strips of Vanderbilt and Washington Avenues offer a mix of bodegas and inveterate neighborhood standbys next to a new spate of hipster-centric bars and restaurants. Turn down any side street, however, and you can encounter gorgeous old brownstones surrounded by quiet greenery."
        }
        if(third == '11209'){
            var descrip3 = "This zipcode belongs to Bay Ridge, the neighborhood where 'Saturday Night Fever' was set. Bay Ridge has resisted the wave of gentrification sweeping through much of Brooklyn. Though becoming popular with a younger crowd, Bay Ridge remains a haven for long-term residents, local businesses and working-class families. The Verrazano-Narrows Bridge dominates the skyline, and single-family row houses make up the majority of the housing stock. Renters pushed out of Park Slope find a similar community vibe here, at a decidedly lower price."
        }
        if(third == '11214' || third=='11204'){
            var descrip3 = "This zipcode belongs to Bensonhurst-- a large, multiethnic neighborhood in the southwestern part of the New York City borough of Brooklyn. It is bounded by 14th Avenue to the northwest, 60th Street and McDonald Avenue to the northeast, 86th Street to the southwest, and 25th Avenue and Avenue P to the southeast. Bensonhurst's adjacent neighborhoods include Dyker Heights to the northwest, Borough Park and Mapleton to the northeast, Bath Beach to the southwest, and Gravesend to the southeast. Bensonhurst is known as a Little Italy of Brooklyn due to its large Italian-American population. Bensonhurst also has the largest population of residents born in China of any neighborhood in New York City and is now home to Brooklyn's second Chinatown."
        }
        if(third == '11228'){
            var descrip3 = "This zipcode belongs to Dyker Heights, a middle-class, largely Italian-American neighborhood in southwestern Brooklyn, that bears signs throughout the year of a place that people deeply care for. In warm-weather months, blocks throw parties — the kind featuring three-legged races and barbecues. In tiny front yards that might have been paved over elsewhere, bushes are neatly trimmed to keep their corkscrew shapes. In December, Dyker Heights — 55,000 residents over one and a half square miles — takes its pride of place to a new and electrifying level. Known as “Dyker Lights,” it’s a vivid tribute to the season, in which yards are filled with a universe of bulbs, garlands, and more than a few life-size “Nutcracker”-style soldiers."
        }
        if(third == '11218'){
            var descrip3 = "This zipcode belongs to Kensington, a predominantly residential area that consists of housing types that run the gamut from brick rowhouses to detached one-family Victorians to apartment buildings. Pre-war brick apartment buildings dominate the Ocean Parkway and Coney Island Avenue frontage, including many that operate as co-ops. The main commercial streets are Coney Island Avenue, Church Avenue, Ditmas Avenue and McDonald Avenue. Kensington is a very diverse neighborhood, containing African-American, Ukrainian, South Asian (Bangladeshi and Pakistani), Chinese, Orthodox Jewish, Hasidic, Irish, Polish, Italian, Albanian, Russian, Latino, Mexican, Australian and Caribbean communities."
        }
        if(third == '11219'){
            var descrip3 = "This zipcode belongs to Borough Park, a neighborhood in the southwestern part of the borough of Brooklyn, in New York City, United States. The neighborhood is bordered by Bensonhurst to the south, Bay Ridge to the southwest, Sunset Park to the west, Kensington and Green-Wood Cemetery to the northeast, Flatbush to the east, and Midwood to the southeast. Borough Park is home to one of the largest Orthodox Jewish communities outside Israel, with one of the largest concentrations of Jews in the United States, and Orthodox traditions rivaling many insular communities. Borough Park is experiencing a sharp growth in population and it is an economically diverse neighborhood."
        }
        if(third == '11230'){
            var descrip3 = "This zipcode belongs to Midwood, a neighborhood in the south-central part of the New York City borough of Brooklyn. It is bounded on the north by the Bay Ridge Branch tracks just above Avenue I and by the Brooklyn College campus of the City University of New York, and on the south by Avenue P and Kings Highway. The eastern border consists of parts of Nostrand Avenue, Flatbush Avenue, and Coney Island Avenue; parts of McDonald Avenue and Ocean Parkway mark the western boundary."
        }
        if(third == '11234'){
            var descrip3 = "This zipcode belongs to Mill Basin, a residential neighborhood in the southeastern part of Brooklyn, New York City. It is located on a peninsula abutting Jamaica Bay and is bordered by Avenue U on the north and the Mill Basin/Mill Island Inlet on the south, east and west. The area is part of Brooklyn Community Board 18. Mill Basin was originally Mill Island, located in Jamaica Bay. In the 17th century, a mill was built on the island by Elbert Elbertse, who occupied Mill Island as well as the nearby Bergen and Barren Islands. Industrial customers started developing the island and connected it to the rest of Brooklyn."
        }
        if(third == '11236'){
            var descrip3 = "This zipcode belongs to Canarsie, a working- and middle-class residential and commercial neighborhood in the southeastern portion of the borough of Brooklyn, in New York City, United States. Canarsie is bordered on the east by Fresh Creek Basin, East 108th Street, and the BMT Canarsie Line (L train); on the north by Linden Boulevard; on the west by Remsen Avenue to Ralph Avenue and the Paerdegat Basin; and on the south by Jamaica Bay. It is adjacent to the East Flatbush, Flatlands, Mill Basin, Bergen Beach, and East New York neighborhoods."
        }
        if(third == '11239'){
            var descrip3 = "This zipcode belongs to Spring Creek. For most of its history Spring Creek was considered the place where 'the city came to an end', consisting of undeveloped marshland used as illegal dumping grounds, and hosting several large landfills and an incinerator during the 20th century. Much of the area was designated as the Fresh Creek Urban Renewal Area in 1967. The area has since seen several major development and restoration projects, including the Starrett City apartment complex, the Gateway Center shopping complex, several affordable housing communities, and Spring Creek Park. Spring Creek had the largest net gain in population in Brooklyn between 1940 and 2010, an increase of 330%."
        }
        if(third == '11223'){
            var descrip3 = "This zipcode belongs to Gravesend, a neighborhood in the south-central section of Brooklyn, on the southwestern edge of Long Island. It is bounded on the south by Coney Island, on the west by Bath Beach, on the north by Bensonhurst, and on the east by Homecrest and Sheepshead Bay. Gravesend was one of the original towns in the Dutch colony of New Netherland. After the English took over, it was one of the six original towns of Kings County in colonial New York. Gravesend was the only English chartered town in what became Kings County, and is notable as being one of the first towns founded by a woman, Lady Deborah Moody. The Town of Gravesend encompassed 7,000 acres in southern Kings County, including the entire island of Coney Island, and was annexed by the City of Brooklyn in 1894. The modern-day neighborhood is part of Brooklyn Community Board 11. As of 2010, Gravesend had a population of 29,436"
        }
        if(third == '11224'){
            var descrip3 = "This zipcode belongs to Coney Island, a residential and commercial neighborhood and entertainment area in the southwestern part of the borough of Brooklyn in New York City. The neighborhood is bounded by Sea Gate to its west, Brighton Beach and Manhattan Beach to its east, Lower New York Bay to the south, and Gravesend to the north. Coney Island was formerly the westernmost of the Outer Barrier islands on the southern shore of Long Island, but in the early 20th century it became a peninsula, connected to the rest of Long Island by land fill. Coney Island has 31,965 residents as of the 2010 United States Census. The neighborhood is ethnically diverse."
        }
        if(third == '11229' || third=='11235'){
            var descrip3 = "This zipcode belongs to Sheepshead Bay, a neighborhood in southern Brooklyn, New York City. It is bounded by Ocean Parkway to the west; Avenue T and Kings Highway to the north; Nostrand Avenue and Gerritsen Avenue to the east; and the Atlantic Ocean to the south. Sheepshead Bay is abutted by the neighborhoods of Brighton Beach and Homecrest to the west; Midwood to the north; and Gerritsen Beach to the east. The neighborhood is named after a bay that separates mainland Brooklyn from the eastern portion of Coney Island, which was originally one of the Outer Barrier islands but is now a peninsula. The mouth of the bay is about 1.0 mile southwest of Marine Park"
        }
        if(third == '11201'){
            var descrip3 = "This zipcode belongs to Brooklyn Heights, which is as well-known for its gorgeous housing stock as for its impressive backdrop and scenery. The Promenade is the neighborhood’s most celebrated and popular public space, offering just about the best views of the Brooklyn Bridge and the Manhattan skyline that can be found. There, you’re likely to find locals walking their Westies, kids zooming around on scooters, and tourists excitedly snapping pics — every one of them savoring the views from this prime perch of a neighborhood. "
        }
        if(third == '11205'){
            var descrip3 = "This zipcode belongs to Clinton Hill, a neighborhood in north-central Brooklyn. It is bordered by the Brooklyn Navy Yard and the Brooklyn-Queens Expressway to the north, Williamsburg to the northeast, Classon Avenue and Bedford–Stuyvesant to the east, Atlantic Avenue and Prospect Heights to the south and southwest and Vanderbilt Avenue and Fort Greene to the west.The neighborhood is served by the NYPD's 88th Precinct.'The Hill', as the general area was known – with a maximum elevation of 95 feet, the highest in the area– was believed to have health benefits because many people believed that disease was more prevalent in low-lying areas. The area is named after Clinton Avenue, which in turn was named in honor of New York Governor DeWitt Clinton (1769–1828). The affluent neighborhood's mixture of apartment buildings, mansions, brownstone and brick rowhouses, and the Pratt Institute and St. Joseph's College, built at various times in a number of different styles, is a great part of its charm. "
        }
        if(third == '11215'){
            var descrip3 = "This zipcode belongs to Park Slope, which has a tranquil, easygoing vibe and can almost feel suburban. Strollers and children of all ages are a constant presence on sidewalks, as are shoppers patronizing local boutiques and dog walkers heading up to the park. Residents are Brooklynites through and through, and tend to be socially conscious, artistically minded and committed to their community. At night, a casual restaurant scene comes alive. For anyone looking for a night out, there are plenty of beer gardens and wine bars to patronize, especially in the South Slope. "
        }
        if(third == '11217'){
            var descrip3 = "This zipcode belongs to Boerum Hill. With wide tree-lined streets, stately Greek revival and Italianate townhouses, and a mix of designer boutiques and upscale restaurants, Boerum Hill exudes an effortlessly elegant appeal. While the neighborhood’s culture, shopping and nightlife rival that of Downtown Manhattan, the clusters of strollers quickly give it away as brownstone Brooklyn. The neighborhood's current atmosphere, however, belies its somewhat gritty history. Until the 1980s, the neighborhood was firmly working class, with many of its largest homes divided into boarding houses or used as union halls. Crime was high, and empty lots abounded. Revitalization efforts, coupled with the neighborhood’s natural assets — its proximity to Manhattan and beautiful housing stock — helped transformed Boerum Hill into one of Brooklyn’s most desirable neighborhoods. With low turnover rates, homes in Boerum Hill are now in constant demand. "
        }
        if(third == '11231'){
            var descrip3 = "This zipcode belongs to Carroll Gardens, which is at once the heart of old-school Brooklyn and a showcase for the borough's brownstone boom. The neighborhood has long been known for its red-sauce Italian joints and lively street life. But now, neighborhood staples like Caputo’s Bake Shop and Monteleone’s Bakery and Café abut upscale stroller shops, yoga studios and fro-yo joints. Despite the newcomers, the neighborhood still feels like a small town, one of the few places where you'll know your neighbors, your postman and your butcher by name. "
        }
        if(third == '11203' || third=='11210'){
            var descrip3 = "This zipcode belongs to East Flatbush, a residential neighborhood in Brooklyn. The area is part of Brooklyn Community Board 17. East Flatbush is patrolled by the NYPD's 67th Precinct. East Flatbush is bounded by Crown Heights and Empire Boulevard to the north; Brownsville and East 98th Street to the east; Flatlands and the Long Island Rail Road's Bay Ridge Branch to the south; and Flatbush and Bedford/Nostrand Avenues to the west. East Flatbush is a predominantly African American neighborhood and has a population of 135,619 as of the 2010 United States Census "
        }
        if(third == '11225'){
            var descrip3 = "This zipcode belongs to Prospect Leffers Gardens, a residential neighborhood in the Flatbush area of Brooklyn. The community is bounded by Empire Boulevard (formerly Malbone Street) to the north, Clarkson Avenue to the south, New York Avenue to the east, and Ocean Avenue/Prospect Park to the west. Prospect Lefferts Gardens was designated a NYC Landmark area in 1979 and called the Prospect Lefferts Gardens Historic District. The neighborhood contains an ethnically diverse community with a largely Caribbean-American and African-American population. Since the 2000s, Prospect Lefferts Gardens has been gentrifying quickly. Real estate development has increased and new residents from other groups have increased "
        }
        if(third == '11226'){
            var descrip3 = "This zipcode belongs to Flatbush, founded in 1651 by Dutch colonists. The neighborhood, which consists of several subsections, had a population of 110,875 as of the 2010 United States Census. Flatbush was a town prior to being incorporated into the City of Brooklyn, and its former border runs through the Brooklyn Botanic Garden. Generally, the township was larger than what is considered Flatbush today by the residents of Brooklyn. The modern neighborhood includes or borders several institutions of note, including Prospect Park and Brooklyn College "
        }
        if(third == '11207' || third=='11208'){
            var descrip3 = "This zipcode belongs to East New York, a residential neighborhood in the eastern section of Brooklyn. Its boundaries, starting from the north and moving clockwise are: Cypress Hills Cemetery to the north, the Borough of Queens to the east, Jamaica Bay to the south, and the Bay Ridge Branch railway tracks next to Van Sinderen Avenue to the west. Linden Boulevard and Atlantic Avenue are the primary thoroughfares through East New York. East New York was founded as the Town of New Lots in the 1650s. It was annexed as the 26th Ward of the rapidly growing City of Brooklyn in 1886, and became part of New York City in 1898. During the latter part of the twentieth century, East New York came to be predominantly inhabited by African Americans and Latinos "
        }
        if(third == '11222'){
            var descrip3 = "This zipcode belongs to the neighborhood Greenpoint. A former industrial and maritime neighborhood, Greenpoint was once primarily home to Polish and Irish immigrants and is now home to a large artist's community. The nightlife, restaurant and music scene have burgeoned in recent years as energy and activity in Williamsburg creeps north towards Greenpoint. Despite all the change that’s happened already and the clear potential for greater change to come, Greenpoint still hangs onto its rich history and an old-school community. Greenpoint maintains a large Polish community and as such has some of the city's best and most authentic butchers. A treasure trove of aging industrial architecture, Greenpoint is also full of impressive old warehouses, brick smokestacks and rusting water tanks. "
        }
        if(third == '11220' || third == '11232'){
            var descrip3 = "This zipcode belongs to the neighborhood Sunset Park. Tucked between Park Slope and Bay Ridge, Sunset Park is a bit of a hike from Manhattan and Downtown Brooklyn. Relative obscurity has kept rents low for decades, although that appears to be slowly changing as brownstone families are priced out of Park Slope and Carroll Gardens. Popular with immigrants, Sunset Park has a thriving Chinese and Latin American community with great restaurants to match. Closer to the water, a new hipster wave is beginning; Industry City, a cluster of 16 warehouses on cobblestone streets, now hosts Smorgasburg, The Brooklyn Flea, and Mister Sunday, a day dance party in the summer. The galleries, tech conferences, rooftop movie screenings and countless artisan shops in that complex are slowly putting Sunset Park on the map for young people "
        }
        if(third == '11221' || third=='11237'){
            var descrip3 = "This zipcode belongs to the neighborhood Bushwick, which has seen a lot of change over the years. In the early 1900s, it was known for its thriving distilleries and breweries. After those industries declined, it experienced a long period of blight through the 1970s and '80s. Now the neighborhood is seeing a renaissance, as artists pushed out of Williamsburg and elsewhere move in and raise property values. Bushwick is a perfect place for those seeking unconventional living spaces: The housing market is full of converted lofts in old factories, sometimes with great access to outdoor space. "
        }
       
    console.log(first)
    console.log(descrip)
    res.send(("1) "+first+"<br>2) "+second+"<br>3)"+third+"<br><br><br>"+"1) " + first+ "--"+descrip + "<br><br> 2) "+second+"--"+ descrip2 +"<br><br> 3) "+third+"--"+descrip3).toString());
    
})

app.listen(3000, function(){
    console.log('Running on port 3000');
})
